[build]
builder = "NIXPACKS"
# Build aşamasında prisma çalıştırma !!
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm start"

[[deploy.hooks]]
command = "cd backend && npx prisma generate"

[[deploy.hooks]]
command = "cd backend && npx prisma migrate deploy"
