[build]
builder = "NIXPACKS"
projectRoot = "."
buildCommand = "npm install"

[deploy]
startCommand = "npm start"

[[deploy.hooks]]
command = "npx prisma generate"

[[deploy.hooks]]
command = "npx prisma migrate deploy"
